<a href="https://colab.research.google.com/github/muhammadsabith960-spec/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np # numerical python

#array = collection of data with same datatype(Homogenious)

#a=np.array([1,2,3.0,4])
a=np.array([1,2,3,4,"a"])
print(a)


['1' '2' '3' '4' 'a']


In [ ]:
#slicing forward slicing backward slicing

b=np.array([1,2,3,4,5,6])
#print(1,2)
print(b[0:2])
#print(5,4)
print(b[-1:-3:-1])

#print(4,5)
print(b[3:])
#print(2,1)
print(b[-5::-1])

[1 2]
[6 5]
[4 5 6]
[2 1]


In [ ]:
#diamension

a=np.array([1,2,3,4,5])
b=np.array([[1,2],[3,4]])
a.ndim  #dimenesion=1 vector
b.ndim #diamension= 2 matrix
print(b)
print(a)
b.shape # to find shape

[[1 2]
 [3 4]]
[1 2 3 4 5]


(2, 2)

In [ ]:
#create a 2x2 matrix 2,3,4,5

a=np.array([[2,3],[4,5]])
print(a)

print(a.shape)
print(a.ndim) # to indetify diamension
print(a.size) #total number of elements

[[2 3]
 [4 5]]
(2, 2)
2
4


In [ ]:
#create a 2x3 matrix and print,size,shape,diamension

a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.size)
print(a.shape)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
6
(2, 3)
2


In [ ]:
# create 4x2 matrix display its size shape diamension
a=np.array([[1,2],[3,4],[5,6],[7,8]])
print(a)
print(a.shape)
print(a.size)
print(a.ndim)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
8
2


In [ ]:
#create a 4x4 matrix display its size shape diamenstion
import numpy as np

a=np.array([[1,2,3,4,],[6,7,8,9],[9,8,4,2],[2,3,5,6]])
print(a)
print(a.shape)
print(a.size)
print(a.ndim)

[[1 2 3 4]
 [6 7 8 9]
 [9 8 4 2]
 [2 3 5 6]]
(4, 4)
16
2


In [ ]:
a[0]

print(a[:,0]) #first row then column
a[1,1]
a[2,2]
a[3,2:]
a[2:,2:]
a[2:,1:3]
a[1:3,3]
a[1:3,0:3]
a[0:,0:]



[1 6 9 2]


array([[1, 2, 3, 4],
       [6, 7, 8, 9],
       [9, 8, 4, 2],
       [2, 3, 5, 6]])

In [ ]:
#zero martix
z=np.zeros([2,3,3],dtype=int) #which means covert into integer,#complex means to convert equation martix
print(z)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [ ]:
#one matrix
z=np.ones([3,3],dtype=int)
print(z)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#create two 2x2 matrix
a=np.array([[1,2],[3,4]])
b=np.array([[3,1],[6,7]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[3 1]
 [6 7]]


In [ ]:
#matrix addition
print(a+b)

#matrix substraction
print(a-b)

#marix multiplication

print(a*b) #not a ,matrix  multiplication


print(a@b) # this is matrix multiplication

print(a.dot(b))#matrix  multiplication

#marix division

print(a/b)

#magic__add__ it is called by magic


[[ 4  3]
 [ 9 11]]
[[-2  1]
 [-3 -3]]
[[ 3  2]
 [18 28]]
[[15 15]
 [33 31]]
[[15 15]
 [33 31]]
[[0.33333333 2.        ]
 [0.5        0.57142857]]


In [ ]:
#full matrix

z=np.full([3,3],4,dtype=int)
print(z)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [ ]:
#create a 3x4 matrix with Value 9 and datatype complex
z=np.full([3,4],9,dtype=complex)
print(z)

[[9.+0.j 9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j 9.+0.j]]


In [ ]:
#identity matrix
#z=np.identity(3,dtype=int)
#print(z)

z=np.eye(3,dtype=int) # two types to print indetity matrix
print(z)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
#create a 4x4 matrix
y=np.array([[1,2,3,4],[5,6,7,8,],[3,4,5,6],[9,8,7,6]])
print(y)
print(y.size)

[[1 2 3 4]
 [5 6 7 8]
 [3 4 5 6]
 [9 8 7 6]]
16


In [ ]:
a=y.reshape(16,1)
print(a)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [3]
 [4]
 [5]
 [6]
 [9]
 [8]
 [7]
 [6]]


In [ ]:
#arange
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [ ]:
#create a 5x2 matrix using arange
a=np.arange(1,11).reshape(5,2)
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
#create a 3x3 matrix with float values
a=np.array([[1.4,2.1,3.5],[4.2,8.5,3.1],[9.6,5.4,4.2]])
print(a)

[[1.4 2.1 3.5]
 [4.2 8.5 3.1]
 [9.6 5.4 4.2]]


In [ ]:
#floor
z=np.floor(a)
print(z)

[[1. 2. 3.]
 [4. 8. 3.]
 [9. 5. 4.]]


In [ ]:
#ceil
z=np.ceil(a)
print(z)

[[ 2.  3.  4.]
 [ 5.  9.  4.]
 [10.  6.  5.]]


In [ ]:
#round

z=np.round(a)    #round  to come 2.5 then go to even numbers
print(z)

[[ 1.  2.  4.]
 [ 4.  8.  3.]
 [10.  5.  4.]]


In [9]:
#create a 3x3 ,matrix
import numpy as np

a=np.arange(1,10).reshape(3,3)
print(a)

a.max()
a.max(axis=1) #numpy=(1,row & 0,column)
a.max(axis=0) #pandas =(0,row & 1,column)
a.min()
a.min(axis=1)
a.min(axis=0)
a.sum()
a.sum(axis=1)
a.sum(axis=0)
np.sqrt(a)  #each element find the root
np.sin(a) #to get cost of each elements
np.tan(a) # to get tan of each elemnets


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

day 3

In [19]:
#flatten()

a.flatten() #to convert into one diamensional array


#sorting

#create a 3x3 matrix

a=np.array([[3,4,1],[5,3,1],[6,9,8]])
a.ndim
print(a)

b=np.sort(a,axis=0) #sorting method

print(b)

c=np.argsort(a,axis=1) #arg (index basic to working function)
print(c)


[[3 4 1]
 [5 3 1]
 [6 9 8]]
[[3 3 1]
 [5 4 1]
 [6 9 8]]
[[2 0 1]
 [2 1 0]
 [0 2 1]]
